### ISSUE TITLE
Pointer

### ISSUE THREAD

**Issue by skynet** [kassner/log-parser#14]
Is it possible to enable a pointer, so that when running this with crond at subsequent cycle it doesn't read the entire log file again? Thanks.

**Comment by kassner** [comment]
I think this library is not in charge of such thing. This means managing and storing information about previous files parsed, but here we just convert a single line into a stdClass object.

**Comment by skynet** [comment]
No, it's actually parsing an entire file, subject to having new items appended. Knowing that there will be new lines in the file after a couple of seconds I need to know where to start at subsequent iteration.

**Comment by kassner** [comment]
I think you could do something like this with fopen, ftell and fseek:

```
$h = fopen('/var/log/nginx/access.log', 'r');

while (!feof($h)) {
   $parser->parse(fgets($h));
}

$lastPosition = ftell($h);
fclose($f);
```

Store the $lastPosition wherever you want and resume the parsing with `fseek($h, $lastPosition)` before the while on the example above.

This solves your problem?

**Comment by skynet** [comment]
yes, thanks, already implemented on my end. would you accept a PR?

**Comment by kassner** [comment]
@skynet if you can provide it in a Iterator or Traversable way will be wonderful.

**Comment by skynet** [comment]
Ok, thanks.

**Comment by MACscr** [comment]
Hope you dont mind me commenting on this, but how would this work when the log file is logrotated? Wouldnt that cause a problem with the $lastPosition?

**Comment by kassner** [comment]
@MACscr It probably will cause some unexpected behaviour, but I never looked into this, I usually don't parse the current access.log file, just old ones.
