### ISSUE TITLE
HTTP/2 ?

### ISSUE THREAD

**Issue by arsenik** [kassner/log-parser#26]
``` 
'%r' => '(?P<request>(?:(?:[A-Z]+) .+? HTTP/(1|2).(?:0|1))|-|)',
```

**Comment by sergey-nagaytsev** [comment]
Here's my actual patch from project fixed right away, applied by [cweagans/composer-patches](https://packagist.org/packages/cweagans/composer-patches):

`build/patches/php/kassner/log-parser/kassner__log-parser__http_2-0.patch`
```diff
--- a/src/Kassner/LogParser/LogParser.php	2018-03-20 10:28:18.757395206 +0300
+++ b/src/Kassner/LogParser/LogParser.php	2018-03-20 10:28:44.192488560 +0300
@@ -22 +22 @@
-        '%r' => '(?P<request>(?:(?:[A-Z]+) .+? HTTP/1.(?:0|1))|-|)',
+        '%r' => '(?P<request>(?:(?:[A-Z]+) .+? HTTP/(1|2).(?:0|1))|-|)',
```

**Comment by kassner** [comment]
@sergey-nagaytsev @arsenik 1.4.0 released with partial HTTP2 support. Let me know if you find something wrong. Thanks!
