### ISSUE TITLE
User name may contain dots, i.e. be a domain name

### ISSUE THREAD

**Issue by mcd-php** [kassner/log-parser#29]
User field in my log contains dots, because users are web sites via api, and logins are domain names.
Nginx is OK with this, so any log parsing software must support this.

Now I changed 'user' field from `%u` to `(?P<user>(?:-|[\w-\.]+))` in my config string, to avoid creating fork.

**Comment by kassner** [comment]
@mcd-php Thanks for reporting it, it is fixed and delivered on `1.3.1`.

Thanks!
