### ISSUE TITLE
Support for apache error log?

### ISSUE THREAD

**Issue by krukru** [kassner/log-parser#34]
Can this parser parse apache error logs?
Error logs have a slightly different format for recording time `[Fri Dec 16 01:46:23 2005] [error] [client 1.2.3.4] Directory index forbidden by rule: /home/test/` then what I can see is expected in access logs `[13/Sep/2006:07:01:53 -0700]`

**Comment by kassner** [comment]
@krukru not really the goal for this library, but you can have a look on the issue #21, which has some explanation on how to use for Nginx's error.log. Should work likewise.

**Comment by krukru** [comment]
That's too bad, it would be very useful to be able to parse both types of apache logs :(
