### ISSUE TITLE
Creation of dynamic property is deprecated on PHP 8.2

### ISSUE THREAD

**Issue by jonasraoni** [kassner/log-parser#64]
When using this package under PHP 8.2, the following warning is emitted `PHP Deprecated: Creation of dynamic property is deprecated`.

**PRs**
- https://github.com/kassner/log-parser/pull/65

**Comment by jonasraoni** [comment]
@kassner

**Comment by kassner** [comment]
Thank you for the report and the PR.

Merged and released on 2.2.0.
